### ISSUE TITLE
Agenda team meeting 2021-09-15

### ISSUE THREAD

**Issue by murillol** [wpmarketingteam/Marcomms-Rolling-tasks#34]

**Comment by abhansnuk** [comment]
2021-09-13 Request for agenda items/ updates sent out 
Agenda published.

**Link to agenda:** https://make.wordpress.org/marketing/2021/09/15/agenda-global-marketing-meeting-15-september-2021/
**Link to meeting timestamp on Slack added:** done 2021/09/18. How to shared with meeting facilitators. 

**Requests:** consider adding the link to the meeting timestamp on Slack onto the agenda on the blog (P2) near the beginning of the meeting to help those less familiar with Slack or having issues finding it. This would be rather than the current practice of adding it after the meeting finishes to help those joining async and other teams prior to the notes being ready and published. 
**Action:** Any changes to the approach to be added to the Agenda macro issue [card] on the board for Rolling Tasks to help others facilitating the meeting.
